### ISSUE TITLE
pg8000 No Longer Supports Python2.

### ISSUE THREAD

**Issue by big-mac-slice** [tk0miya/testing.postgresql#28]
Looks like the 1.13.0 release of pg8000 drops support of python2.7 which is being picked up by the requirement of `pg8000 >= 1.10`.

**Comment by asqui** [comment]
Just encountered this as well. PR submitted.

The last PR accepted by this project was Oct 31, 2017 so I don't know how long it will take to get this incorporated?

**Comment by piroux** [comment]
The last release of `pg8000` indeed dropped Python 2 support but that should not have broken anything for Python 2.7 projects, so that I reported the issue to the maintainer and he fixed the releases on Pypi quite quickly:
https://github.com/tlocke/pg8000/issues/7

So the good thing is that `testing.postgresql` does not need to pin the version of `pg8000`.

**Comment by big-mac-slice** [comment]
I saw, thanks @piroux! Unpinned our project's pg8000 and it's back to working. Appreciated.
